
import bpy, math, random, json, os
import numpy as np

# ── Data path (auto-generated by Jupyter) ─────────────────────
DATA_PATH  = r"C:\Users\Mordecai\Desktop\claude\backrooms_project\outputs\heightmaps"
HMAP_FILE  = os.path.join(DATA_PATH, "heightmap_data.json")

with open(HMAP_FILE) as f:
    all_hmaps = json.load(f)

liminal  = all_hmaps.get("liminal", [])[:6]
pool     = all_hmaps.get("pool",    [])[:4]
selected = [("liminal", h) for h in liminal] + [("pool", h) for h in pool]
print(f"Loaded {len(selected)} heightmaps")

# ── Clear scene ───────────────────────────────────────────────
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()
for b in bpy.data.meshes:    bpy.data.meshes.remove(b)
for b in bpy.data.materials: bpy.data.materials.remove(b)

# ── Materials ─────────────────────────────────────────────────
def make_mat(name, color, rough=0.88, metal=0.0, emit=0.0):
    mat  = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = next(n for n in mat.node_tree.nodes if n.type=="BSDF_PRINCIPLED")
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Roughness"].default_value  = rough
    bsdf.inputs["Metallic"].default_value   = metal
    if emit > 0:
        for inp in bsdf.inputs:
            if inp.name == "Emission Color":    inp.default_value = color
            if inp.name == "Emission Strength": inp.default_value = emit
    return mat

mat_liminal = make_mat("Liminal", (0.82, 0.78, 0.68, 1), rough=0.92)
mat_pool    = make_mat("Pool",    (0.58, 0.72, 0.76, 1), rough=0.38)

# ── Heightmap → solid slab ────────────────────────────────────
def hmap_to_slab(flat, size, name, mat,
                 slab_w=7.0, slab_d=7.0,
                 min_h=0.3, max_h=2.5, res=18):
    # Resample heightmap to res x res
    arr  = np.array(flat).reshape(size, size)
    rows = np.linspace(0, size-1, res).astype(int)
    cols = np.linspace(0, size-1, res).astype(int)
    hmap = arr[np.ix_(rows, cols)]

    verts, faces = [], []

    # Top surface
    for r in range(res):
        for c in range(res):
            x = (c/(res-1) - 0.5) * slab_w
            y = (r/(res-1) - 0.5) * slab_d
            z = min_h + float(hmap[r,c]) * (max_h - min_h)
            verts.append((x, y, z))

    # Bottom surface (flat)
    bot = len(verts)
    for r in range(res):
        for c in range(res):
            x = (c/(res-1) - 0.5) * slab_w
            y = (r/(res-1) - 0.5) * slab_d
            verts.append((x, y, 0.0))

    # Top faces
    for r in range(res-1):
        for c in range(res-1):
            i = r*res + c
            faces.append((i, i+1, i+res+1, i+res))

    # Bottom faces
    for r in range(res-1):
        for c in range(res-1):
            i = bot + r*res + c
            faces.append((i+res, i+res+1, i+1, i))

    # Side walls
    for c in range(res-1):
        t, b = c, bot+c
        faces.append((t, t+1, b+1, b))
    for c in range(res-1):
        t = (res-1)*res+c
        b = bot+(res-1)*res+c
        faces.append((b, b+1, t+1, t))
    for r in range(res-1):
        t, b = r*res, bot+r*res
        faces.append((b+res, b, t, t+res))
    for r in range(res-1):
        t = r*res+(res-1)
        b = bot+r*res+(res-1)
        faces.append((t, b, b+res, t+res))

    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    obj.data.materials.append(mat)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.shade_smooth()
    return obj

# ── Build slabs ───────────────────────────────────────────────
print("Building solid slabs...")
slabs = []
for idx, (label, hm) in enumerate(selected):
    mat = mat_liminal if label == "liminal" else mat_pool
    w   = random.uniform(5.0, 9.0)
    d   = random.uniform(5.0, 9.0)
    obj = hmap_to_slab(
        hm["flat"], hm["size"],
        name  = f"Slab_{label}_{idx}",
        mat   = mat,
        slab_w= w, slab_d= d,
        min_h = random.uniform(0.2, 0.4),
        max_h = random.uniform(1.5, 3.0),
        res   = 18
    )
    slabs.append((obj, label, w, d))
    print(f"  Slab {idx+1}: {label} {w:.1f}x{d:.1f}m")

# ── Stack into mountain unit ──────────────────────────────────
print("Stacking into mountain unit...")
history = []

for i, (obj, label, w, d) in enumerate(slabs):
    ratio  = i / max(len(slabs)-1, 1)
    spread = (1.0 - ratio) * 2.5

    if i == 0:
        x, y, z = 0.0, 0.0, 0.0
    else:
        px, py, pz, pw, pd = history[-1]
        x = px + random.uniform(-spread, spread)
        y = py + random.uniform(-spread, spread)
        z = pz + random.uniform(1.0, 2.2)

    rot_z = random.uniform(-0.3, 0.3) * (0.5 + ratio)
    rot_x = random.uniform(-0.12, 0.12) * ratio
    rot_y = random.uniform(-0.12, 0.12) * ratio

    obj.location       = (x, y, z)
    obj.rotation_euler = (rot_x, rot_y, rot_z)

    s = 1.0 - ratio * 0.3
    obj.scale = (s, s, 1.0)

    history.append((x, y, z, w*s, d*s))
    print(f"  Layer {i+1}: z={z:.1f} offset={x:.1f},{y:.1f} rot={math.degrees(rot_z):.0f}deg")

# ── Camera ────────────────────────────────────────────────────
bpy.ops.object.camera_add(location=(22, -20, 18))
cam = bpy.context.active_object
cam.rotation_euler     = (math.radians(52), 0, math.radians(42))
cam.data.lens          = 50
bpy.context.scene.camera = cam

# ── Lighting ─────────────────────────────────────────────────
bpy.ops.object.light_add(type="SUN", location=(15, -10, 25))
sun = bpy.context.active_object
sun.data.energy    = 6.0
sun.data.color     = (1.0, 0.97, 0.88)
sun.rotation_euler = (math.radians(38), 0, math.radians(28))

bpy.ops.object.light_add(type="AREA", location=(-10, 8, 12))
fill = bpy.context.active_object
fill.data.energy = 1000
fill.data.color  = (0.55, 0.70, 1.00)
fill.data.size   = 12

bpy.ops.object.light_add(type="SPOT", location=(2, 14, 8))
rim = bpy.context.active_object
rim.data.energy    = 1500
rim.data.color     = (0.88, 0.94, 1.00)
rim.data.spot_size = math.radians(35)
rim.rotation_euler = (math.radians(58), 0, math.radians(175))

world = bpy.context.scene.world
world.use_nodes = True
bg = world.node_tree.nodes["Background"]
bg.inputs[0].default_value = (0.0, 0.0, 0.0, 1)
bg.inputs[1].default_value = 0.0

bpy.context.scene.render.engine       = "CYCLES"
bpy.context.scene.cycles.samples      = 128
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
print("Done! F12 to render.")
